name: Production
on: [push]
jobs:
  Production_Tests:
    runs-on: ubuntu-22.04
    steps: 
      - name: Checkout
        uses: actions/checkout@v6
      - name: Cypress run
        uses: npm run production:test