name: Production
on: [push]
jobs:
  Production_Tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npx cypress run --spec 'cypress/e2e/production/*'